  language: python
  python:
    - 3.6
    - nightly
  before_install:
    - pip install pytest pytest-cov coveralls
  install:
    - python setup.py -q install
  script:
    - pytest -v --cov emupy2600 
  after_success:
    - coveralls

